### PR TITLE
added support for share plain text in ios

### PR DESCRIPTION
**Pull request by npomfret**
* added ios support for sharing text (using NSExtensionActivationSupportsText) 
* call reject if exception happens 
* reformatted ReactNativeShareExtension.m using standard xcode formatting

### CODE REVIEW

**Comment by npomfret** [comment]
@alinz this allows the user to select text in an iOS app and share to your react-native app.  I didn't make an android change because it already appears to be supported.

**Comment by npomfret** [comment]
FYI - the change looks bigger than it is - I reformatted the code using Xcode so there's some white space changes.

**Comment by alinz** [comment]
This is awesome, Sorry for late response. Would you like to help me out maintaining this repo?

**Comment by npomfret** [comment]
Sure thing

**Pull request merged**
