### PR TITLE
Add iOS device troubleshooting section to README.

### PR DESCRIPTION
**Pull request by TheTekton**
Troubleshooting the app extension on device can be quite challenging.

- [x] Update README.
  - [x] Add iOS troubleshooting section.
    - [x] Add guidance for separating app/extension bundles.

### CODE REVIEW

**Comment by TheTekton** [comment]
Will try to push a commit with guidance for separating app/extension bundles by this weekend.

**Comment by alinz** [comment]
Thanks man, ping me here once you done!

**Comment by TheTekton** [comment]
@alinz This should be ready for you to review when you're able.

**Comment by TheTekton** [comment]
Need to fork, or are you just busy?

**Comment by alinz** [comment]
Thanks,

**Comment by ebaynaud** [comment]
@TheTekton do you have an updated `react-native-xcode.sh` for 0.59?

**Pull request merged**
