### PR TITLE
Multiple data type

### PR DESCRIPTION
**Pull request by arribbar**
- Add support for audio and video files
- Get real path from downloaded content as whatsapp thanks to @cbjs.
- Support multi files sharing thanks to @cbjs
- Return now an array to android part

### CODE REVIEW

**Comment by arribbar** [comment]
Question: It seems indentation in JAVA part is a mess. What are the rules ? :)

**Comment by alinz** [comment]
@arribbar if you can use the Android Studio source formatter and send a PR i would merge it with code.

**Comment by arribbar** [comment]
@alinz Done! Thank you!

**Comment by arribbar** [comment]
@alinz Would it be possible to merge it ? (or tell me if anything is wrong ?)

**Comment by arribbar** [comment]
@alinz ?

**Comment by alinz** [comment]
@arribbar been a little bit busy with stuff, do we have this feature in iOS?

**Comment by arribbar** [comment]
We cannot get several medias with iOS but we can save video, images or text with iOS with what is done for now.
I have a limited knowledge on iOS but I can work on this feature if you want to

**Comment by alinz** [comment]
@arribbar I'm gonna hold off on this, I want the api on both end be exactly the same on both platform. Need a little bit more time to rethink about it.

**Comment by arribbar** [comment]
All right. I am going to work on iOS side to be the same. I'll let you know when it is ready @alinz .

**Pull request closed without merging**
